#!/usr/bin/env python3
"""Generate a deterministic sample wardrobe JSON (and Kotlin insert block) for StyleDrop.

Usage:
    python3 scripts/generate_sample_wardrobe.py --count 24 --out fixtures/sample_wardrobe.json
    python3 scripts/generate_sample_wardrobe.py --kotlin           # print Kotlin seed code

Mirrors the real WardrobeItem entity fields exactly:
id, imageUrl, category, type, color, secondaryColor, style, fit, pattern,
season, brand, timesWorn, isFavoriteItem, lastWorn, createdAt
"""
from __future__ import annotations

import argparse
import json
import random
from pathlib import Path

CATEGORIES = ["Tops", "Bottoms", "Shoes", "Outerwear", "Accessories", "Bags", "Watches", "Jewelry"]
STYLES = ["Streetwear", "Casual", "Minimalist", "Old Money", "Y2K", "Korean",
          "Smart Casual", "Formal", "Sporty", "Vintage", "Techwear", "Grunge"]
PATTERNS = ["Plain", "Striped", "Graphic", "Checked", "Camo"]
FITS = ["Oversized", "Slim", "Regular", "Relaxed"]
SEASONS = ["All Season", "Summer", "Winter", "Spring/Fall"]

TYPES = {
    "Tops": ["Oversized T-Shirt", "Oxford Shirt", "Hoodie", "Knit Sweater", "Polo Shirt"],
    "Bottoms": ["Straight Jeans", "Chino Trousers", "Cargo Pants", "Tailored Shorts"],
    "Shoes": ["White Sneakers", "Leather Boots", "Suede Loafers", "Running Shoes"],
    "Outerwear": ["Black Bomber Jacket", "Wool Overcoat", "Denim Trucker Jacket"],
    "Accessories": ["Wool Cap", "Leather Belt", "Silk Scarf", "Sunglasses"],
    "Bags": ["Canvas Tote", "Leather Satchel", "Nylon Backpack"],
    "Watches": ["Field Watch", "Chronograph", "Dress Watch"],
    "Jewelry": ["Silver Chain", "Signet Ring", "Beaded Bracelet"],
}

# ivory / quiet-luxury palette from ui/theme/Color.kt
PALETTE = ["#1B1A17", "#FFFFFF", "#F1ECE1", "#4A463E", "#B08A4F", "#16 150F".replace(" ", ""),
           "#1B2A4A", "#C19A6B", "#556B2F", "#7A3E4A", "#46688C", "#8B4513"]

NOW = 1_760_000_000_000


def build(count: int, seed: int = 42) -> list[dict]:
    rng = random.Random(seed)
    items: list[dict] = []
    for i in range(count):
        cat = CATEGORIES[i % len(CATEGORIES)]
        items.append({
            "id": f"sample-{i:03d}",
            "imageUrl": f"content://styledrop/sample/{i:03d}.jpg",
            "category": cat,
            "type": rng.choice(TYPES[cat]),
            "color": rng.choice(PALETTE),
            "secondaryColor": "" if rng.random() < 0.7 else rng.choice(PALETTE),
            "style": rng.choice(STYLES),
            "fit": rng.choice(FITS),
            "pattern": rng.choice(PATTERNS),
            "season": rng.choice(SEASONS),
            "brand": rng.choice(["Uniqlo", "COS", "Zara", "Arket", "Everlane", ""]),
            "timesWorn": rng.randint(0, 40),
            "isFavoriteItem": rng.random() < 0.25,
            "lastWorn": None if rng.random() < 0.3 else NOW - rng.randint(1, 60) * 86_400_000,
            "createdAt": NOW - i * 3_600_000,
        })
    return items


def as_kotlin(items: list[dict]) -> str:
    lines = ["// Auto-generated by scripts/generate_sample_wardrobe.py — deterministic fixture"]
    lines.append("val sampleWardrobe = listOf(")
    for it in items:
        last = "null" if it["lastWorn"] is None else f"{it['lastWorn']}L"
        lines.append(
            f'  WardrobeItem(id = "{it["id"]}", imageUrl = "{it["imageUrl"]}", '
            f'category = "{it["category"]}", type = "{it["type"]}", color = "{it["color"]}", '
            f'secondaryColor = "{it["secondaryColor"]}", style = "{it["style"]}", '
            f'fit = "{it["fit"]}", pattern = "{it["pattern"]}", season = "{it["season"]}", '
            f'brand = "{it["brand"]}", timesWorn = {it["timesWorn"]}, '
            f'isFavoriteItem = {str(it["isFavoriteItem"]).lower()}, lastWorn = {last}, '
            f'createdAt = {it["createdAt"]}L),'
        )
    lines.append(")")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--count", type=int, default=24)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--out", type=str, default=None)
    ap.add_argument("--kotlin", action="store_true")
    args = ap.parse_args()

    items = build(args.count, args.seed)
    if args.kotlin:
        print(as_kotlin(items))
        return
    out = Path(args.out) if args.out else Path("fixtures/sample_wardrobe.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(items, indent=2), encoding="utf-8")
    print(f"wrote {len(items)} items -> {out}")


if __name__ == "__main__":
    main()
